In [3]:
import numpy as np

#converting list to array
lst = [1,2,3,4]
arr = np.array(lst)
print(arr)
arr.shape     #shows rows and columns

[1 2 3 4]


(4,)

In [18]:
import numpy as np

arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[12,13,14,15]])
arr1.shape
arr1[2]= 2,5,7,9  #for updating at particular index
print(arr1)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 2  5  7  9]
 [12 13 14 15]]


In [19]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 2,  5,  7,  9],
       [12, 13, 14, 15]])

In [20]:
arr1.shape

(4, 4)

In [21]:
arr1[1:3,1:3]  # for range if want particular row column data

array([[6, 7],
       [5, 7]])

In [23]:
arr1[0:2,1::2]  # for skipping in between table

array([[2, 4],
       [6, 8]])

In [31]:
arr1[2] = arr1[2][::-1]  # Reverses the elements of the 3rd row (index 2)
print(arr1)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9  7  5  2]
 [12 13 14 15]]


In [33]:
arr1[:,1].shape
#When you select a single column from a 2D array like arr1[:,1], NumPy automatically reduces its dimensionality. Instead of giving you a (4, 1) 2D array (a column vector), it returns a 1D array with 4 elements, hence the shape (4,)

(4,)

In [34]:
arr1<2

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [36]:
arr1[arr1>2] #give specific values

array([ 3,  4,  5,  6,  7,  8,  9,  7,  5, 12, 13, 14, 15])

In [42]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  7,  5,  2],
       [12, 13, 14, 15]])

In [41]:
arr1.reshape(2,8)
# shape according to yourself

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9,  7,  5,  2, 12, 13, 14, 15]])

In [49]:
arr2 = np.arange(1,20,2)
arr2    # aranges value according to range and steps


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [53]:
arr2.shape
arr2.reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [58]:
arr2*4  #multiplies each value

array([ 4, 12, 20, 28, 36, 44, 52, 60, 68, 76])

In [64]:
arr3=arr2*arr2
arr3

array([  1,   9,  25,  49,  81, 121, 169, 225, 289, 361])

In [67]:
arr3.reshape(2,5)

array([[  1,   9,  25,  49,  81],
       [121, 169, 225, 289, 361]])

In [69]:
#ones and zeroes

np.ones((3,4))
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [77]:
#randint: give range and will select randomly and specify how many numbers you want
np.random.randint(10,33,6)

array([22, 27, 17, 27, 23, 30])

In [81]:
#randn:gives -0 to 1 values in the given shape acc to SD MEAN = 0 and DEVIATION = 1
np.random.randn(3,3)

array([[-1.41149134, -0.08428443, -0.02005911],
       [ 0.07266731, -0.38871711, -0.12566591],
       [-0.2269378 ,  0.52180949, -2.33132772]])

In [83]:
#random_sample:gives 0 to 1 values in the given shape
np.random.random_sample((4,7))


array([[0.81639057, 0.01110647, 0.63158804, 0.24951861, 0.57823018,
        0.11865984, 0.48045019],
       [0.46385626, 0.99714729, 0.49762231, 0.58039172, 0.86537944,
        0.69259634, 0.5638252 ],
       [0.25204008, 0.36998549, 0.58929696, 0.91867675, 0.89398813,
        0.14770135, 0.72354814],
       [0.94308265, 0.85499994, 0.53806785, 0.29712671, 0.60751699,
        0.98851921, 0.70155315]])